import 'bootstrap';
import './sass/main.scss';
import './scripts/classRender.js';
import './scripts/apiService.js';
import './scripts/modal.js';
import './scripts/teamCard.js';
import './scripts/pagination.js';
import './scripts/authForm.js';
import './scripts/switchTheme.js';
import './scripts/arrowUp.js';
// import './scripts/firebase.js';