import './sass/library.scss';
import './scripts/modal.js';
import './scripts/teamCard.js';
import './scripts/authForm.js';
import './scripts/classRenderAuthUsers.js';
import './scripts/switchTheme.js';
import './scripts/arrowUp.js';
import './scripts/menu.js';
import 'bootstrap';
